#!/bin/bash
#
# Cria miniaturas a partir da primeira página de um PDF
#
echo "Bash ${BASH_VERSION}"
if [ -f "$1" ]; then
	if [[ "$1" == *.pdf ]]; then
		if [ $# -gt 1 ] && [ $2 -gt 1 ]; then
			pdftoppm "$1" "$(basename "$1" .pdf)1" -png -f $2 -singlefile
		else
			pdftoppm "$1" "$(basename "$1" .pdf)1" -png -f 1 -singlefile
		fi
		convert "$(basename "$1" .pdf)1.png" "$(basename "$1" .pdf)1.jpg"
		convert "$(basename "$1" .pdf)1.png" -resize 50% "$(basename "$1" .pdf)2.png"
		convert "$(basename "$1" .pdf)1.png" -resize 50% "$(basename "$1" .pdf)2.jpg"
	else
		echo "Arquivo '$1' não é um PDF."
	fi
else
	echo "Arquivo '$1' não encontrado."
fi
